### ISSUE TITLE
Session id

### ISSUE THREAD

**Issue by xsploit** [hissincn/suno-ai#6]
for some reason it wont get session id

**Comment by hissincn** [comment]
I'll fix it soon.Thx for point out.

**Comment by Gringouze** [comment]
Hey, it's just a number version of clerk needed. ( https://github.com/hissincn/suno-ai/pull/7/files )

**Comment by CKGrafico** [comment]
looks like this issue is closed right?

**Comment by xsploit** [comment]
yes
